# -*- coding: utf-8 -*-
"""Manipulación y Análisis de Datos Abiertos.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103SihhaSz8A3jC_ARNU-3CJXMqUQMgf3
"""

import pandas as pd
import numpy as np

df = pd.read_csv(
    '/content/drive/MyDrive/Colab Notebooks/202500.csv',
    encoding="latin1",
    sep=",",
    quotechar='"',
    engine="python",
    on_bad_lines='skip'
)

df.shape

df.head()

df[['cod_institucion','institucion']] = df['Institucion'].str.split(' - ', n=1, expand=True)

df.replace(['-','00 - -','000 - -'], np.nan, inplace=True)

df.head()

df.info()

df.duplicated().sum()

df.shape

df = df[df['Vigente'] > 0]
df.shape

df.groupby('institucion')['Vigente'].sum()

df = df.drop(columns=[col for col in df.columns if 'Dia-' in col])
df.columns

df['porcentaje_ejecucion'] = df['Ejecucion_Acumulada'] / df['Vigente']

df.columns

instituciones_vig=df.groupby('institucion')['Vigente'].sum().sort_values(ascending=False)
mejores_inst=instituciones_vig.head(10)
mejores_inst

import matplotlib.pyplot as plt
mejores_inst = mejores_inst / 1e9
mejores_inst.plot(kind='bar')
plt.title('Las 10 instituciones con mayor presupuesto')
plt.ylabel('Presupuesto (miles de millones)')
plt.xticks(rotation=90)
plt.show()

porcentaje = instituciones_vig / instituciones_vig.sum()
top10_pct = porcentaje.head(10)

top10_pct.plot(kind='pie', autopct='%1.1f%%')
plt.title('Distribución del presupuesto de los primeros 10')
plt.ylabel('')
plt.show()

eficiencia = df.groupby('institucion').agg({'Vigente':'sum','Ejecucion_Acumulada':'sum'})
eficiencia['ratio'] = eficiencia['Ejecucion_Acumulada'] / eficiencia['Vigente']

eficiencia.sort_values('ratio', ascending=False).head(10)['ratio'].plot(kind='bar')
plt.title('Instituciones con mayor ejecución')
plt.show()

df[['cod_finalidad','finalidad']] = df['Finalidad'].str.split(' - ', n=1, expand=True)

sector = df.groupby('finalidad')['Vigente'].sum().sort_values(ascending=False)
print(sector.head(10))

sector.head(10).plot(kind='bar')
plt.title('Presupuesto por finalidad')
plt.ylabel('Presupuesto Vigente')
plt.xticks(rotation=90)
plt.show()